//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laba4_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public int IdBrand { get; set; }
        public int IdType { get; set; }
        public string Name { get; set; }
    
        public virtual Type Type { get; set; }
    }
}
