//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laba2_Books_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int BookId { get; set; }
        public int PublishingId { get; set; }
        public int AuthorId { get; set; }
        public int GenreId { get; set; }
        public int ProviderId { get; set; }
        public string Name { get; set; }
        public System.DateTime DateOfPubl { get; set; }
        public int Numb { get; set; }
        public decimal Price { get; set; }
        public System.DateTime DateProv { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Obkl { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Publishing Publishing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
